name: Check Sonarwube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download ccov XML from artifact
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
          path: code-coverage.xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}